version: '3'

services:
    nginx-node:
        restart: always
        image: finizco/nginx-node:latest
        ports:
        - "8080:8080"
        environment:
        - NODE_PORT=3000
        - NODE_MODE=prod
        volumes:
        - ./app:/app
